#!/bin/bash
echo "***************************"
echo " "
echo "Hello $USER"
echo " "
echo "***************************"

echo "--- Setting Finnish keyboard layout ---"
setxkbmap fi

echo "--- Setting Finnish timezone ---"
sudo timedatectl set-timezone Europe/Helsinki

echo "--- Installing Git, Tree, Puppet and Puppetmaster ---"
sudo apt-get update

echo "--- Creation of "git" directory in users "home" directory ---"
sudo apt-get install -y tree puppet

echo "--- Changing Puppet configurations ---"
sudo grep ^server /etc/puppet/puppet.conf || echo -e "\n[agent]\nserver=puppetmaster\n" |sudo tee -a /etc/puppet/puppet.conf

echo "-- Configuring "/etc/hosts" directory--"
sudo grep puppetmaster /etc/hosts || echo -e "\n192.168.223.134 puppetmaster\n"|sudo tee -a /etc/hosts

echo "-- Starting Puppet --"
sudo puppet agent --enable
sudo puppet agent --test
sudo service puppet start
sudo service puppet restart